// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyCheck.DataAcess.EntityFramework;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyCheck.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyCheck.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<decimal>("AccountBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", "MoneyCheck");
                });

            modelBuilder.Entity("MoneyCheck.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountId1")
                        .HasColumnType("integer");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CategoryOperationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CategorySum")
                        .HasColumnType("numeric");

                    b.HasKey("CategoryId");

                    b.HasIndex("AccountId1")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountId" }, "Category_AccountId")
                        .IsUnique();

                    b.ToTable("Categories", "MoneyCheck");
                });

            modelBuilder.Entity("MoneyCheck.Models.Operation", b =>
                {
                    b.Property<int>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperationId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Operation");
                });

            modelBuilder.Entity("MoneyCheck.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("UserId");

                    b.ToTable("Users", "MoneyCheck");
                });

            modelBuilder.Entity("MoneyCheck.Models.Account", b =>
                {
                    b.HasOne("MoneyCheck.Models.User", "UserNavigation")
                        .WithMany("UserAccounts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UsersAccount_Users_UserId");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("MoneyCheck.Models.Category", b =>
                {
                    b.HasOne("MoneyCheck.Models.Account", "Account")
                        .WithOne("CategoryNavigation")
                        .HasForeignKey("MoneyCheck.Models.Category", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoneyCheck.Models.Account", null)
                        .WithOne("AccountCategories")
                        .HasForeignKey("MoneyCheck.Models.Category", "AccountId1");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MoneyCheck.Models.Operation", b =>
                {
                    b.HasOne("MoneyCheck.Models.Category", "Category")
                        .WithMany("CategoryOperations")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_CategoryOperations_Category_CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MoneyCheck.Models.Account", b =>
                {
                    b.Navigation("AccountCategories")
                        .IsRequired();

                    b.Navigation("CategoryNavigation")
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyCheck.Models.Category", b =>
                {
                    b.Navigation("CategoryOperations");
                });

            modelBuilder.Entity("MoneyCheck.Models.User", b =>
                {
                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
